@startuml

title __HELPER's Class Diagram__\n

  namespace de.gerweckweb.helper {
    class de.gerweckweb.helper.ConnectDatabase {
        - databaseName : String
        - password : String
        - port : int
        - serverName : String
        - username : String
        + ConnectDatabase()
        + connectDatabaseAndExecuteQuery()
        {static} + connectWithNewUserLogin()
        + createDatabaseUrl()
        + getDatabaseName()
        + getPassword()
        + getPort()
        + getServerName()
        + getUsername()
        + setDatabaseName()
        + setPassword()
        + setPort()
        + setServerName()
        + setUsername()
        - getHeadingText()
        - printDatabaseOutputOnConsole()
        - printRequestedOutputOnConsole()
    }
  }
  

  namespace de.gerweckweb.helper {
    class de.gerweckweb.helper.Keyboard {
        {static} + BETWEEN : String
        {static} ~ input : Scanner
        {static} ~ strInput : String
        {static} + contains()
        {static} + getCharacter()
        {static} + guiReadInt()
        {static} + guiReadInt()
        {static} + readDouble()
        {static} + readDouble()
        {static} + readDoubleFromGui()
        {static} + readDoubleFromGui()
        {static} + readInteger()
        {static} + readInteger()
        {static} + tryKeyword()
        {static} + userInput()
        {static} + userInput()
        {static} - isValueBetweenMinMax()
        {static} - parseGuiValueToDouble()
        {static} - parseOnlyWhenDoubleInRange()
        {static} - printValueAfterCheckForValid()
        {static} - tryGuiValueBetweenMinMax()
        {static} - tryParseTextFieldToDouble()
        {static} - tryToParseGuiValueToInt()
        {static} - tryToParsoToIntBetweenMinMax()
    }
  }
  

  namespace de.gerweckweb.helper {
    class de.gerweckweb.helper.KeyboardTester {
        {static} + main()
    }
  }
  

  namespace de.gerweckweb.helper {
    enum Keywords {
      CLEAR
      EXIT
      RESTART
    }
  }
  

  namespace de.gerweckweb.helper {
    class de.gerweckweb.helper.Logins {
        - password : String
        - username : String
        + Logins()
        + Logins()
        + getPassword()
        + getUsername()
    }
  }
  

  namespace de.gerweckweb.helper {
    class de.gerweckweb.helper.RestartApplications {
        {static} + SUN_JAVA_COMMAND : String
        {static} + restartApplication()
        {static} - addProgramArgs()
        {static} - checkArgumentForAgentLib()
        {static} - checkForJarOrClassPath()
        {static} - excecuteCommandInShutdownHook()
        {static} - exceuteSomeCostums()
    }
  }
  

  namespace de.gerweckweb.helper {
    class de.gerweckweb.helper.SimpleGui {
        ~ jbtnDoButton : JButton
        ~ jlControlOutput : JLabel
        ~ jtfTextEntry : JTextField
        + actionPerformed()
        ~ SimpleGui()
    }
  }
  

  de.gerweckweb.helper.SimpleGui .up.|> java.awt.event.ActionListener
  de.gerweckweb.helper.SimpleGui -up-|> javax.swing.JFrame


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
